# Generated by Django 4.1.5 on 2023-01-19 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_candidate_cv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consult',
            old_name='bussiness_sector',
            new_name='business_sector',
        ),
    ]
