# Generated by Django 4.1.5 on 2023-01-20 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_bussiness_sector_consult_business_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='deadline',
            field=models.DateField(null=True),
        ),
    ]
