# Generated by Django 4.1.5 on 2023-01-26 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_blog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='benefits',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='career',
            name='plus',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='career',
            name='requirement',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='career',
            name='role_responsibility',
            field=models.TextField(null=True),
        ),
    ]
