# Generated by Django 4.1.5 on 2023-01-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_color_alter_career_benefits_alter_career_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='hex_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
