# Generated by Django 4.1.6 on 2023-02-02 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_blog_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='slug',
            new_name='slug_blog',
        ),
    ]
