# Generated by Django 4.1.6 on 2023-02-02 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_rename_slug_blog_slug_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug_blog',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
