# Generated by Django 4.1.6 on 2023-02-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_career_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='active',
        ),
        migrations.AddField(
            model_name='career',
            name='status',
            field=models.IntegerField(choices=[(1, 'active'), (0, 'Inactive')], default=1),
        ),
    ]
